SimpleCarCatalogue.Gui/Models/ErrorViewModel.cs
using System;

namespace SimpleCarCatalogue.Gui.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SimpleCarCatalogue.Gui/ViewModels/CarSetViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SimpleCarCatalogue.Gui.ViewModels
{
    public class CarSetViewModel
    {
        public Guid? Id { get; set; }
        public List<Producer> Producers { get; set; }
        public Car Car { get; set; }
    }
}

SimpleCarCatalogue.Gui/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SimpleCarCatalogue.Gui.ViewModels;
using SimpleCarCatalogue.Repositories;

namespace SimpleCarCatalogue.Gui.Controllers
{
    public class CarsController : Controller
    {
        private readonly ICarContext _context;
        private readonly ICarService _carService;

        public CarsController(ICarContext context, ICarService carService)
        {
            _context = context;
            _carService = carService;
        }

        // GET: Cars
        public IActionResult Index()
        {
            return View();
        }

        // GET: api/Get
        [HttpGet]
        public IEnumerable<Car> Get()
        {
            return _carService.GetAll(); ;
        }

        // GET: Cars/Create
        public IActionResult Create()
        {
            var carSetViewModel = new CarSetViewModel
            {
                Producers = _context.Producers.ToList(),
                Car = new Car(),
            };
            return View(carSetViewModel);
        }

        // POST: Cars/Create  
        [HttpPost]
        public IActionResult Create([FromForm] Car car)
        {
            _carService.Create(car);
            return RedirectToAction(nameof(Index));
        }

        // GET: Cars/Edit/5
        public IActionResult Edit(Guid id)
        {
            var car = _carService.Get(id);

            var vm = new CarSetViewModel
            {
                Car = car,
                Id = car.Id,
                Producers = _context.Producers.ToList(),
            };
            return View(vm);
        }

        // POST: Cars/Edit/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public IActionResult Edit(Guid id, Car car)
        {
            _carService.Edit(car);

            return RedirectToAction(nameof(Index));
        }

        // DELETE: Cars/Delete/5
        [HttpDelete("Cars/Delete/{id}")]
        public void Delete(Guid id)
        {
            _carService.Delete(id);
        }
    }
}

SimpleCarCatalogue.Gui/Controllers/ErrorsController.cs
using System;
using System.Net;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SimpleCarCatalogue.Exceptions;

namespace SimpleCarCatalogue.Gui.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    public class ErrorsController : Controller
    {
        public void Error()
        {
            var context = HttpContext.Features.Get<IExceptionHandlerFeature>();
            var exception = context?.Error;

            var statusCode = HttpStatusCode.InternalServerError;
            if (exception is ObjectNotExistsException)
                statusCode = HttpStatusCode.NotFound;
            else if (exception is ArgumentException)
                statusCode = HttpStatusCode.BadRequest;

            Response.StatusCode = (int)statusCode;
            Response.WriteAsync(exception.Message);
        }
    }
}

SimpleCarCatalogue.Gui/Views/Cars/Create.cshtml
@model CarSetViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Car</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form id="car-set-form" asp-action="Create">
            @await Html.PartialAsync("_SetCar", Model)
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

SimpleCarCatalogue.Gui/Views/Cars/Edit.cshtml
@model CarSetViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Car</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form id="car-set-form" asp-action="Edit">
            <input type="hidden" asp-for="@Model.Car.Id" />
            @await Html.PartialAsync("_SetCar", Model)
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

SimpleCarCatalogue.Gui/Views/Cars/Index.cshtml
@model IEnumerable<SimpleCarCatalogue.Car>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>


<table id="cars-data-table"
       data-url="cars/get">
</table>

<div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div id="delete-modal-id" class="hide"></div>
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete <span id="delete-modal-title">id</span>?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button id="delete-car-button" type="button" class="btn btn-danger">Delete</button>
            </div>
        </div>
    </div>
</div>

SimpleCarCatalogue.Gui/Views/Cars/_SetCar.cshtml
@model CarSetViewModel

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="form-group">
    <label asp-for="@Model.Car.Name" class="control-label"></label>
    <input asp-for="@Model.Car.Name" class="form-control" />
    <span asp-validation-for="@Model.Car.Name" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="@Model.Car.Description" class="control-label"></label>
    <textarea asp-for="@Model.Car.Description" class="form-control"></textarea>
    <span asp-validation-for="@Model.Car.Description" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="@Model.Car.Year" class="control-label"></label>
    <input asp-for="@Model.Car.Year" class="form-control" />
    <span asp-validation-for="@Model.Car.Year" class="text-danger"></span>
</div>
<div class="form-group form-check">
    <label class="form-check-label">
        <input class="form-check-input" asp-for="@Model.Car.IsDeleted" /> @Html.DisplayNameFor(model => model.Car.IsDeleted)
    </label>
</div>

<div class="form-group">
    <label class="edit-label">Producer <span class="required"></span></label>
    <div>

        @Html.DropDownListFor(
             x => x.Car.ProducerId,
             new SelectList(Model.Producers, "Id", "Name", Model.Car.ProducerId),
             "-- Select --"
        )
    </div>
    <span asp-validation-for="@Model.Car.ProducerId" class="text-danger"></span>
</div>

SimpleCarCatalogue.Gui/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Car Catalogue</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Cars" asp-action="Index">Car Catalogue</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SimpleCarCatalogue.Gui - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.18.0/bootstrap-table.min.js" integrity="sha512-r+k0ZHRS62LiRIFpBwrwQ14MIT9YPusK7AcoeT34gHdzh2p7FBmU43/aE2ZDem9NM7bSIbMMV23u6zYny28oqg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.18.0/locale/bootstrap-table-en-US.min.js" integrity="sha512-t6Sh/zpgdIfOQu4/mH8QUhK85SIU6t6pOI5eGcgHugj6k4m5S2tb96X6GKKa7b4fR9nV0tPOVpqbwPU6gaT6vQ==" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.18.0/bootstrap-table.min.css" integrity="sha512-9+eWL83icQU9EurxdlXQjhqhQbq/wtbpoQZiWp73jXRHw5cIshFkSw5/d0XOXuQe9AjmWeOQfvdgu/WAA4KDVw==" crossorigin="anonymous" />
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>